import assert from "node:assert/strict";
import { cpSync, mkdtempSync, mkdirSync, readFileSync, renameSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import os from "node:os";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { buildDelegationRequest, delegationIdentity, emitIfAuthorized, isApprovedSolIdentity, isFreshChildObserverSnapshot, isFreshChildPostTurnSummary, isFreshChildStartupSummary, loadContract, RunController, runIfAuthorized, sha256, SOL_ACTOR, summarizeSessionEntries, validateContract, validateWorkerJson } from "../controller.mjs";
import { checkPreflight, isPermissionSystemExtension, SHIPPED_AGENT_FILE_SHA256 } from "../preflight-assert.mjs";
import { buildAssistedChildRow, buildBaselineChildRow, providerCountersValid } from "./pilot-accounting.mjs";
import { resolvePinnedPiEntry } from "./pi-entry.mjs";

function fixture(cwd) { return { version: 2, authorityId: "a1", expiresAt: new Date(Date.now() + 60_000).toISOString(), cwd, model: "openai-codex/gpt-5.6-sol", agentDefinitionDigest: "a".repeat(64), agentDefinitionProjectionVersion: 2, nodes: [{ id: "n1", actor: SOL_ACTOR, task: "Return JSON.", expectedJson: { ok: true }, timeoutMs: 1000 }] }; }
function loaded() { const cwd = mkdtempSync(path.join(tmpdir(), "autonoxis-")); const text = JSON.stringify(fixture(cwd)); const file = path.join(cwd, "contract.json"); writeFileSync(file, text); return loadContract(file, sha256(text), cwd); }
async function observerHelpers() {
  const agentDir = process.env.PI_CODING_AGENT_DIR || path.join(os.homedir(), ".pi", "agent"), anchor = path.join(agentDir, "npm", "package.json");
  const jiti = createRequire(anchor)("jiti")(anchor, { interopDefault: true });
  return await jiti.import(path.resolve("./test/observer.ts"));
}
function observerContext(entries) { return { cwd: "/tmp/fresh", sessionManager: { getSessionId: () => "child", getEntries: () => entries }, getSystemPrompt: () => "" }; }
async function livePreflight() {
  const runRoot = mkdtempSync(path.join(tmpdir(), "autonoxis-preflight-"));
  const agentDir = process.env.PI_CODING_AGENT_DIR || path.join(os.homedir(), ".pi", "agent");
  const anchor = path.join(agentDir, "npm", "package.json"), resolve = createRequire(anchor).resolve;
  const { entry: piEntry } = resolvePinnedPiEntry();
  const jiti = createRequire(anchor)("jiti")(anchor, { interopDefault: true, alias: { "@earendil-works/pi-coding-agent": piEntry } });
  const [preflight, ceiling, required] = await Promise.all(["preflight", "capability-ceiling", "required-child-extensions"].map(name => jiti.import(`pi-subagents/${name}`)));
  const plugin = path.resolve("."), nodeModules = path.join(runRoot, ".pi", "npm", "node_modules");
  mkdirSync(nodeModules, { recursive: true }); symlinkSync(plugin, path.join(nodeModules, "pi-autonoxis"), "dir");
  const observerPath = path.resolve("./test/observer.ts"), sessionId = "preflight-test";
  const observer = required.registerRequiredChildExtensions({ sessionId, extensions: [{ id: "autonoxis-observer", path: observerPath }] });
  const cap = ceiling.registerSubagentCapabilityCeiling({ sessionId, source: "test", ceiling: { allowedTools: [], allowedAgents: [SOL_ACTOR] } });
  try { const result = await preflight.resolveSubagentLaunchContract({ agent: SOL_ACTOR, task: "Return {}", cwd: runRoot, context: "fresh", model: "openai-codex/gpt-5.6-sol", thinking: "off", skill: false, artifacts: false, parentSessionId: sessionId, sessionDir: path.join(runRoot, ".pi", "preflight"), availableModels: [{ provider: "openai-codex", id: "gpt-5.6-sol" }], capabilityCeiling: ceiling.resolveCurrentSubagentCapabilityCeiling(sessionId), intercomBridge: { mode: "off" } }); return { result, observerPath }; } finally { cap.dispose(); observer.dispose(); }
}

test("AC2 contract hash and schema are mandatory", () => { const run = loaded(); assert.equal(run.contract.nodes.length, 1); assert.throws(() => loadContract(run.path, "0".repeat(64), run.contract.cwd), /contract_hash_mismatch/); assert.throws(() => validateContract({ ...run.contract, model: "other" }), /contract_schema_invalid/); });
test("AC3 policy must dispatch before a node can launch", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.begin(c.loaded.contract.nodes[0]); assert.throws(() => c.admit("ASK"), /policy_not_authorized/); });
test("AC5 accepts only the exact base-to-off terminal identity and ignores duplicates", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); const node = c.loaded.contract.nodes[0]; const current = c.begin(node); c.admit("DISPATCH"); c.markDispatched(); const response = { ...current, status: "completed", model: "openai-codex/gpt-5.6-sol:off", launchContractDigest: "d", result: { kind: "text", text: '{"ok":true}' } }; assert.equal(c.terminal(response, node.expectedJson, "d", c.loaded.contract.model).ok, true); assert.equal(c.terminal(response, node.expectedJson, "d", c.loaded.contract.model).ignored, true); });
test("AC5 exact model identity rejects every non-off representation", () => { const base = "openai-codex/gpt-5.6-sol"; assert.equal(isApprovedSolIdentity(base, `${base}:off`, "off"), true); for (const value of [base, `${base}:low`, `${base}:medium`, `${base}:high`, `${base}:off:off`, `${base}:offx`, "openai/gpt-5.6-sol:off", "openai-codex/gpt-5.6-solx:off", " openai-codex/gpt-5.6-sol:off", "openai-codex/GPT-5.6-sol:off", null, undefined, 1]) assert.equal(isApprovedSolIdentity(base, value, "off"), false, String(value)); assert.equal(isApprovedSolIdentity(base, `${base}:off`, "high"), false); assert.equal(isApprovedSolIdentity(base, `${base}:off`), true); });
test("AC2 observer requires fresh startup plus one persisted post-turn", async () => { const entries = JSON.parse(readFileSync(new URL("./pilot2-child-session-summary.json", import.meta.url), "utf8")), { snapshotStartup, capturePostTurn } = await observerHelpers(), collector = { snapshots: [], observerId: "autonoxis-observer", observerHash: "untrusted-parent-value" }; const startup = snapshotStartup({ getActiveTools: () => [] }, observerContext(entries.slice(0, 2)), collector); collector.snapshots.push(startup); assert.deepEqual(startup.startupEntrySummary, summarizeSessionEntries(entries.slice(0, 2))); assert.equal(startup.observerHash, sha256(readFileSync(new URL("./observer.ts", import.meta.url)))); assert.notEqual(startup.observerHash, collector.observerHash); assert.equal(isFreshChildStartupSummary(startup.startupEntrySummary), true); assert.equal(isFreshChildObserverSnapshot(startup), false); capturePostTurn(observerContext(entries), collector); const completed = collector.snapshots[0]; assert.equal(isFreshChildPostTurnSummary(completed.postTurnEntrySummary), true); assert.equal(isFreshChildObserverSnapshot(completed), true); capturePostTurn(observerContext(entries), collector); assert.equal(isFreshChildObserverSnapshot(collector.snapshots[0]), false); for (const [start, end] of [[entries.slice(0, 2), [...entries, entries[4]]], [[...entries.slice(0, 2), entries[3]], entries], [[entries[1]], entries], [entries.slice(0, 2), [{ type: "custom" }, ...entries]], [entries.slice(0, 2), [...entries.slice(0, 3), entries[4], entries[3]]]]) { const next = snapshotStartup({ getActiveTools: () => [] }, observerContext(start), collector), local = { snapshots: [next], observerId: "autonoxis-observer", observerHash: "h" }; capturePostTurn(observerContext(end), local); assert.equal(isFreshChildObserverSnapshot(local.snapshots[0]), false); } });
test("AC2 observer scopes provider counters to the selected parent and child snapshots away from it", async () => {
  const observerModule = await observerHelpers(), hooks = new Map();
  observerModule.default({ on: (name, handler) => hooks.set(name, handler), getActiveTools: () => [] });
  const key = Symbol.for("pi-autonoxis.observer.v1"), collector = { parentSessionId: "parent", providerRequests: { before: 0, after: 0 }, snapshots: [], observerId: "autonoxis-observer", observerHash: "h" };
  globalThis[key] = collector;
  const context = (id, entries = []) => ({ cwd: "/tmp/fresh", sessionManager: { getSessionId: () => id, getEntries: () => entries }, getSystemPrompt: () => "" });
  try {
    hooks.get("before_provider_request")({}, context("child")); hooks.get("after_provider_response")({}, context("child"));
    assert.deepEqual(collector.providerRequests, { before: 0, after: 0 });
    hooks.get("before_provider_request")({}, context("parent")); hooks.get("after_provider_response")({}, context("parent"));
    assert.deepEqual(collector.providerRequests, { before: 1, after: 1 });
    hooks.get("session_start")({}, context("parent", [{ type: "model_change" }])); assert.equal(collector.snapshots.length, 0);
    hooks.get("session_start")({}, context("child", [{ type: "model_change" }, { type: "thinking_level_change" }])); assert.equal(collector.snapshots.length, 1);
    hooks.get("agent_end")({}, context("child", [{ type: "model_change" }, { type: "thinking_level_change" }, { type: "session_info" }, { type: "message", message: { role: "user" } }, { type: "message", message: { role: "assistant", provider: "openai-codex", model: "gpt-5.6-sol", responseModel: "gpt-5.6-sol", providerThinkingLevel: "off" } }]));
    assert.equal(collector.snapshots[0].postTurnCaptureCount, 1);
  } finally { delete globalThis[key]; }
});

test("AC6 worker JSON requires semantic and byte-canonical exactness", () => { assert.equal(validateWorkerJson('{"ok":true}', { ok: true }).ok, true); assert.equal(validateWorkerJson('{"ok":false}', { ok: true }).ok, false); assert.equal(validateWorkerJson('{"b":2,"a":1}', { a: 1, b: 2 }).ok, false); assert.equal(validateWorkerJson('{"__proto__":{}}', {}).ok, false); assert.equal(validateWorkerJson('{"ok":"\\u0001"}', { ok: "\u0001" }).ok, false); });
test("AC5 stop revokes authority and blocks future dispatch", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.stop(); assert.throws(() => c.begin(c.loaded.contract.nodes[0]), /authority_expired/); });
test("AC5 stop preserves the exact dispatched identity for cancellation", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); const current = c.begin(c.loaded.contract.nodes[0]); c.admit("DISPATCH"); c.markDispatched(); assert.deepEqual(c.stop(), { requestId: current.requestId, ownerRunId: current.ownerRunId, nodeId: current.nodeId }); const terminal = c.terminal({ ...current, status: "cancelled" }, {}, "d", "m"); assert.equal(terminal.ignored, false); assert.equal(terminal.ok, false); assert.equal(c.state, "CANCELLED"); });

test("AC5 accepts requestId-only invalid_request as a rejection terminal", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); const current = c.begin(c.loaded.contract.nodes[0]); c.admit("DISPATCH"); c.markDispatched(); assert.deepEqual(c.terminal({ requestId: current.requestId, status: "invalid_request" }, {}, "d", "m"), { ignored: false, ok: false, reason: "terminal_evidence_invalid" }); });
test("AC6 rejects symlinked contract path components", () => { const root = mkdtempSync(path.join(tmpdir(), "autonoxis-root-")); const outside = mkdtempSync(path.join(tmpdir(), "autonoxis-outside-")); mkdirSync(path.join(root, "contracts")); symlinkSync(outside, path.join(root, "contracts", "linked")); const text = JSON.stringify(fixture(root)); writeFileSync(path.join(outside, "contract.json"), text); assert.throws(() => loadContract("contracts/linked/contract.json", sha256(text), root), /contract_file_invalid/); });
test("AC2 delegation DTOs retain only public request fields and the cancel triple", () => { const identity = { requestId: "r", ownerRunId: "o", nodeId: "n" }; const request = buildDelegationRequest(identity, { agent: "a", task: "t", context: "fresh", cwd: "/tmp", model: "openai-codex/gpt-5.6-sol", thinking: "off", timeoutMs: 1, toolBudget: { hard: 0, block: "*" }, skill: false, artifacts: false, intercomBridge: { mode: "off" }, result: { kind: "text" } }); const supported = new Set(["requestId", "ownerRunId", "nodeId", "agent", "task", "context", "cwd", "model", "thinking", "timeoutMs", "toolBudget", "skill", "artifacts", "intercomBridge", "result"]); assert.ok(Object.keys(request).every(key => supported.has(key))); assert.deepEqual(delegationIdentity(identity), identity); assert.throws(() => delegationIdentity({ requestId: "r", nodeId: "n" }), /delegation_identity_invalid/); const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.begin(c.loaded.contract.nodes[0]); assert.equal(c.stop(), undefined); });
test("AC5 stop before dispatch revokes authority", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.begin(c.loaded.contract.nodes[0]); c.stop(); assert.throws(() => c.admit("DISPATCH"), /authority_expired/); });
test("AC5 final emit gate rejects revocation after second preflight", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.begin(c.loaded.contract.nodes[0]); c.admit("DISPATCH"); c.stop(); let emitted = false; assert.throws(() => emitIfAuthorized(c, () => { emitted = true; }), /authority_expired/); assert.equal(emitted, false); });
test("AC5 policy gate prevents a request after preflight revocation", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.begin(c.loaded.contract.nodes[0]); c.stop(); let requested = false; assert.throws(() => runIfAuthorized(c, () => { requested = true; }), /authority_expired/); assert.equal(requested, false); });
test("AC5 rejects mismatched optional invalid-request identities and late generations", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); const first = c.begin(c.loaded.contract.nodes[0]); c.admit("DISPATCH"); c.markDispatched(); assert.equal(c.terminal({ requestId: first.requestId, ownerRunId: "wrong", status: "invalid_request" }, {}, "d", "m").ignored, true); c.interruptUnknown(); const second = c.begin(c.loaded.contract.nodes[0]); c.admit("DISPATCH"); c.markDispatched(); assert.equal(c.terminal({ ...first, status: "cancelled" }, {}, "d", "m").ignored, true); assert.equal(c.current.requestId, second.requestId); });
test("AC3 rejects a second active node", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1 }); c.begin(c.loaded.contract.nodes[0]); assert.throws(() => c.begin(c.loaded.contract.nodes[0]), /run_busy/); });
test("AC6 rejects outside and oversize contracts", () => { const root = mkdtempSync(path.join(tmpdir(), "autonoxis-root-")); const outside = mkdtempSync(path.join(tmpdir(), "autonoxis-outside-")); const text = JSON.stringify(fixture(root)); const outsideFile = path.join(outside, "contract.json"); writeFileSync(outsideFile, text); assert.throws(() => loadContract(outsideFile, sha256(text), root), /contract_path_outside_cwd/); const oversized = path.join(root, "oversized.json"); writeFileSync(oversized, " ".repeat(65537)); assert.throws(() => loadContract(oversized, sha256(" ".repeat(65537)), root), /contract_file_invalid/); });
test("AC6 rejects noncanonical duplicate, deep, and large-number JSON", () => { const duplicate = validateWorkerJson('{"ok":false,"ok":true}', { ok: true }); assert.equal(duplicate.ok, false); assert.equal(duplicate.format_canonical, false); const deep = "[".repeat(18) + "0" + "]".repeat(18); assert.equal(validateWorkerJson(deep, []).ok, false); assert.equal(validateWorkerJson("9007199254740992", 9007199254740992).ok, false); assert.equal(validateWorkerJson('{"bad\\u0001":true}', {}).ok, false); });
test("AC2 gate zero refuses before native loading", () => { const harness = new URL("./native-harness.mjs", import.meta.url); const result = spawnSync(process.execPath, [harness.pathname, "assert-host"], { env: { ...process.env, PI_SUBAGENT_CHILD: "1" }, encoding: "utf8" }); assert.equal(result.status, 1); assert.match(result.stderr, /LIVE PENDING FOR PARENT: child_inert/); });
test("AC2 plain Node imports public preflight through Pi's pinned alias", () => { const harness = new URL("./native-harness.mjs", import.meta.url); const result = spawnSync(process.execPath, [harness.pathname, "assert-api"], { env: { ...process.env, PI_SUBAGENT_CHILD: "1", PI_SUBAGENTS_HERDR_BRIDGE: "0" }, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); assert.match(result.stdout, /PUBLIC_API_READY/); });
test("AC2 configured package agent resolves through public preflight", () => { const harness = new URL("./native-harness.mjs", import.meta.url); const runRoot = mkdtempSync(path.join(tmpdir(), "autonoxis-configured-")); const env = { ...process.env, PI_SUBAGENT_CHILD: "1", PI_SUBAGENTS_HERDR_BRIDGE: "0" }; const identity = spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", runRoot], { env, encoding: "utf8" }); assert.equal(identity.status, 0, identity.stderr); const agent = JSON.parse(identity.stdout); const fixturePath = path.join(runRoot, "fixture.json"); writeFileSync(fixturePath, JSON.stringify({ ...fixture(runRoot), agentDefinitionDigest: agent.definitionDigest })); const result = spawnSync(process.execPath, [harness.pathname, "assert-configured-agent", "--run-root", runRoot, "--fixture", fixturePath], { env, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); assert.match(result.stdout, /CONFIGURED_AGENT_RESOLVED/); const mismatchRoot = mkdtempSync(path.join(tmpdir(), "autonoxis-configured-mismatch-")); const mismatch = spawnSync(process.execPath, [harness.pathname, "assert-configured-agent", "--run-root", mismatchRoot, "--fixture", fixturePath], { env, encoding: "utf8" }); assert.notEqual(mismatch.status, 0); });
test("AC2 only print-agent-identity accepts agent-dir", () => { const harness = new URL("./native-harness.mjs", import.meta.url); const result = spawnSync(process.execPath, [harness.pathname, "assert-configured-agent", "--agent-dir", path.resolve(".")], { env: { ...process.env, PI_SUBAGENT_CHILD: "1", PI_SUBAGENTS_HERDR_BRIDGE: "0" }, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /agent_dir_only_supported_for_print_identity/); });
test("AC2 harness refuses non-temporary and unowned nonempty run roots", () => { const harness = new URL("./native-harness.mjs", import.meta.url), env = { ...process.env, PI_SUBAGENT_CHILD: "1", PI_SUBAGENTS_HERDR_BRIDGE: "0" }; const nonempty = mkdtempSync(path.join(tmpdir(), "autonoxis-nonempty-")); writeFileSync(path.join(nonempty, "keep"), "do not touch"); const occupied = spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", nonempty], { env, encoding: "utf8" }); assert.notEqual(occupied.status, 0); assert.match(occupied.stderr, /run_root_not_empty/); assert.equal(readFileSync(path.join(nonempty, "keep"), "utf8"), "do not touch"); const unowned = mkdtempSync(path.join(tmpdir(), "autonoxis-unowned-")); mkdirSync(path.join(unowned, ".pi")); const refused = spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", unowned], { env, encoding: "utf8" }); assert.notEqual(refused.status, 0); assert.match(refused.stderr, /run_root_not_owned/); const outsideTemp = spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", path.parse(tmpdir()).root], { env, encoding: "utf8" }); assert.notEqual(outsideTemp.status, 0); assert.match(outsideTemp.stderr, /run_root_not_disposable/); });
test("AC2 harness refuses package and settings collisions without replacement", () => { const harness = new URL("./native-harness.mjs", import.meta.url), childEnv = { ...process.env, PI_SUBAGENT_CHILD: "1", PI_SUBAGENTS_HERDR_BRIDGE: "0" }; const packageRoot = mkdtempSync(path.join(tmpdir(), "autonoxis-package-collision-")); assert.equal(spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", packageRoot], { env: childEnv, encoding: "utf8" }).status, 0); const link = path.join(packageRoot, ".pi", "npm", "node_modules", "pi-autonoxis"); unlinkSync(link); mkdirSync(link); writeFileSync(path.join(link, "keep"), "foreign"); const packageCollision = spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", packageRoot], { env: childEnv, encoding: "utf8" }); assert.notEqual(packageCollision.status, 0); assert.match(packageCollision.stderr, /run_root_package_collision/); assert.equal(readFileSync(path.join(link, "keep"), "utf8"), "foreign"); const settingsRoot = mkdtempSync(path.join(tmpdir(), "autonoxis-settings-collision-")); assert.equal(spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", settingsRoot], { env: childEnv, encoding: "utf8" }).status, 0); const settings = path.join(settingsRoot, ".pi", "settings.json"); writeFileSync(settings, "foreign-settings"); const parentEnv = { ...process.env, PI_SUBAGENT_CHILD: "0", PI_SUBAGENTS_HERDR_BRIDGE: "0", PI_SUBAGENTS_LLM_INTENT_ARBITER: "0" }; const settingsCollision = spawnSync(process.execPath, [harness.pathname, "check", "--run-root", settingsRoot, "--fixture", path.resolve("./test/fixture.json")], { env: parentEnv, encoding: "utf8" }); assert.notEqual(settingsCollision.status, 0); assert.match(settingsCollision.stderr, /settings_collision/); assert.equal(readFileSync(settings, "utf8"), "foreign-settings"); });
test("AC2 public preflight assertion rejects configured-agent tampering", async () => { const { result, observerPath } = await livePreflight(); const impostor = path.join(mkdtempSync(path.join(tmpdir(), "autonoxis-impostor-")), "sol-leaf.md"); writeFileSync(impostor, "impostor"); const digest = result.contract.agent.definitionDigest; assert.deepEqual(checkPreflight(result, observerPath, digest).resolvedModel, "openai-codex/gpt-5.6-sol:off"); assert.equal(checkPreflight(result, observerPath, digest).thinking, "off"); const reject = mutate => { const value = structuredClone(result); mutate(value); assert.throws(() => checkPreflight(value, observerPath, digest), /preflight_rejected/); }; const accept = mutate => { const value = structuredClone(result); mutate(value); assert.doesNotThrow(() => checkPreflight(value, observerPath, digest)); }; accept(value => { value.contract.thinkingCeiling = "low"; }); for (const model of ["openai-codex/gpt-5.6-sol", "openai-codex/gpt-5.6-sol:low", "openai-codex/gpt-5.6-sol:medium", "openai-codex/gpt-5.6-sol:high", "openai-codex/gpt-5.6-sol:off:off", "openai/gpt-5.6-sol:off", "openai-codex/gpt-5.6-sol:off "]) reject(value => { value.contract.model = model; }); reject(value => { value.contract.thinking = "low"; }); reject(value => { value.contract.tools.disableAmbientExtensions = false; }); reject(value => { value.contract.diagnostics.push({ severity: "host-required" }); }); reject(value => { value.contract.agent.filePath = impostor; }); reject(value => { value.contract.agent.definitionDigest = "0".repeat(64); }); reject(value => { value.contract.agent.source = "user"; }); reject(value => { value.contract.agent.shadowedCandidates.push("impostor"); }); reject(value => { value.contract.tools.configuredExtensions.push("evil"); }); reject(value => { value.contract.tools.runtimeExtensions.push("/tmp/evil.ts"); value.contract.tools.extensionArgs.push("/tmp/evil.ts"); }); reject(value => { value.contract.tools.requiredExtensionIds = []; }); reject(value => { value.contract.tools.excludeTools = []; }); assert.throws(() => checkPreflight(result, observerPath), /preflight_expected_digest_invalid/); assert.throws(() => checkPreflight(result, observerPath, null), /preflight_expected_digest_invalid/); assert.equal(isPermissionSystemExtension(path.join(tmpdir(), "missing-extension.ts")), false); });
test("AC5 racing terminal after revocation is rejected and timeout tombstones", () => { const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => 1, monotonic: () => 1 }); const current = c.begin(c.loaded.contract.nodes[0]); c.admit("DISPATCH"); c.markDispatched(); c.stop(); const race = c.terminal({ ...current, status: "completed", model: "openai-codex/gpt-5.6-sol:off", launchContractDigest: "d", result: { kind: "text", text: '{"ok":true}' } }, { ok: true }, "d", "openai-codex/gpt-5.6-sol"); assert.equal(race.ok, false); assert.equal(race.reason, "authority_expired"); assert.equal(c.state, "CANCELLED"); c.interruptUnknown(); assert.equal(c.state, "INTERRUPTED_UNKNOWN"); assert.equal(c.current, undefined); });
test("AC3 detects wall-clock rollback against monotonic elapsed time", () => { let wall = 10_000, mono = 0; const c = new RunController({ loaded: loaded(), sessionId: "s", now: () => wall, monotonic: () => mono }); wall = 9_000; mono = 2_001; assert.throws(() => c.assertAuthority(), /clock_rollback_detected/); });
test("AC7 verify-ledger binds raw artifact journal, identities, and provider counters", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "autonoxis-ledger-")), evidence = path.join(dir, "pilot.json"), attemptsDir = path.join(dir, "attempts"); mkdirSync(attemptsDir);
  const runtimePath = path.join(dir, "runtime-contract.json"), runtime = "{\"fixture\":\"frozen\"}"; writeFileSync(runtimePath, runtime);
  const agent = { definitionDigest: "c".repeat(64), definitionProjectionVersion: 2 }, observerPath = "/tmp/observer.ts", observerHash = "a";
  const registration = { id: "autonoxis-observer", path: observerPath, hash: observerHash };
  const preflight = { launchContractDigest: "d", resolvedModel: "openai-codex/gpt-5.6-sol:off", thinking: "off", effectiveAllowlist: [], internalTools: [], effectiveMcpTools: [], fanoutAuthorized: false, ambientExtensionsDisabled: true, diagnostics: [], requiredExtensionIds: ["autonoxis-observer"], requiredPathOmitted: true, capabilityAudit: {}, agent };
  const measure = decision => ({ decision, durationMs: 1, promptBytes: 1, responseEvalCount: null });
  const child = (arm, sessionId, identity) => {
    const terminal = { ...identity, status: "completed", model: "openai-codex/gpt-5.6-sol:off", usage: { input: 1, output: 1, cacheRead: 0, cacheWrite: 0 }, launchContractDigest: "d" };
    const observer = { sessionId, tools: [], cwd: "/tmp", startupEntrySummary: [{ type: "model_change" }, { type: "thinking_level_change" }], postTurnEntrySummary: [{ type: "model_change" }, { type: "thinking_level_change" }, { type: "session_info" }, { type: "message", role: "user" }, { type: "message", role: "assistant", provider: "openai-codex", model: "gpt-5.6-sol", responseModel: "gpt-5.6-sol", providerThinkingLevel: "off" }], postTurnCaptureCount: 1, bridgeActive: false, observerId: "autonoxis-observer", observerHash };
    if (arm === "baseline") return buildBaselineChildRow({ arm, terminal, outputHash: "a".repeat(64), observer, observerPath, observerHash, preflight, ...identity });
    return buildAssistedChildRow({ terminalEntry: { data: { ...terminal, outputHash: "a".repeat(64), formatCanonical: true, observer, observerRegistration: registration, preflight, agent } }, transport: { requests: [identity], terminals: [terminal] }, contractHash: "h", node: { data: { localPolicy: { conductor: measure("DISPATCH"), manager: measure("ACCEPT") } } } }).row;
  };
  const parent = (arm, phase) => ({ arm, phase, status: "completed", provider: "openai-codex", model: "gpt-5.6-sol", responseModel: "gpt-5.6-sol", providerThinkingLevel: "off", responses: [{ provider: "openai-codex", model: "gpt-5.6-sol", responseModel: "gpt-5.6-sol", providerThinkingLevel: "off" }], usage: { input: 1, output: 1, cacheRead: 0, cacheWrite: 0 }, usageMissing: false });
  const rows = [parent("baseline", "parent-1"), parent("baseline", "parent-2"), child("baseline", "child-1", { requestId: "r1", ownerRunId: "o1", nodeId: "n1" }), parent("assisted", "setup"), child("assisted", "child-2", { requestId: "r2", ownerRunId: "o2", nodeId: "n2" })];
  const specs = [
    { arm: "baseline", phase: "parent-1", premium: true, row: rows[0] }, { arm: "baseline", phase: "parent-2", premium: true, row: rows[1] }, { arm: "baseline", phase: "child", premium: true, row: rows[2] }, { arm: "assisted", phase: "setup", premium: true, row: rows[3] }, { arm: "assisted", phase: "command", premium: false }, { arm: "assisted", phase: "child", premium: true, row: rows[4], contractHash: sha256(runtime) }
  ];
  const write = (file, record) => { const bytes = `${JSON.stringify(record, null, 2)}\n`; writeFileSync(file, bytes); return { path: file, sha256: sha256(bytes) }; };
  const artifacts = specs.map((spec, index) => {
    const sequence = index + 1, base = { arm: spec.arm, phase: spec.phase, premium: spec.premium }, childIdentity = spec.row?.phase === "child" ? { requestId: spec.row.requestId, ownerRunId: spec.row.ownerRunId, nodeId: spec.row.nodeId } : {};
    const issuedIdentity = sequence === 6 ? { nodeId: spec.row.nodeId, contractHash: spec.contractHash } : childIdentity;
    const requestedIdentity = spec.premium ? { requestedModel: "openai-codex/gpt-5.6-sol", requestedThinking: "off" } : {};
    const terminal = spec.row ? { ...spec.row, ...childIdentity, ...(spec.row.phase === "child" ? { unresolved: false } : {}) } : { status: "completed", usage: null, usageMissing: true, providerBefore: { before: 1, after: 0 }, providerAfter: { before: 1, after: 0 }, rawMessageCount: 0, transportRequests: 1 };
    const outcome = { accepted: true, ...childIdentity, ...(spec.row?.phase === "child" ? { unresolved: false, validation: { ok: true, format_canonical: spec.row.formatCanonical } } : {}) };
    const file = kind => path.join(attemptsDir, `${String(sequence).padStart(3, "0")}-${kind}.json`);
    return { sequence, premium: spec.premium, issued: write(file("issued"), { ...base, ...issuedIdentity, ...requestedIdentity, sequence, kind: "issued", timestamp: "t" }), terminal: write(file("terminal"), { ...base, ...terminal, sequence, kind: "terminal", timestamp: "t" }), outcome: write(file("outcome"), { ...base, ...outcome, sequence, kind: "outcome", timestamp: "t" }) };
  });
  const reservationPath = `${evidence}.reservation.json`; const reservation = write(reservationPath, { kind: "pilot-evidence-reservation", timestamp: "t", evidencePath: evidence });
  const complete = { status: "PILOT_COMPLETE", fixtureHash: "b".repeat(64), pinnedAgentDefinitionDigest: agent.definitionDigest, pinnedAgentDefinitionProjectionVersion: 2, runtimeContractHash: sha256(runtime), runtimeContract: { path: runtimePath, sha256: sha256(runtime) }, evidenceReservation: reservation, elapsedMs: 1, premiumAttemptsObserved: 5, attemptArtifacts: artifacts, usage: rows, hp1: { piLevelOnly: true, activeTools: [] }, providerRequests: { baseline: { before: 2, after: 0 }, assisted: { before: 1, after: 0 } }, noWake: { assistedCommandAddedMessages: 0, graceMs: 5000, providerRequests: { before: { before: 1, after: 0 }, after: { before: 1, after: 0 } } }, limits: { maxPremiumAttempts: 8, maxMinutes: 15, admissionTokens: 32000 }, accounting: { price: "UNKNOWN", savings: "NOT_CALCULATED", setupContextCacheConfound: true } };
  const harness = new URL("./native-harness.mjs", import.meta.url), env = { ...process.env, PI_SUBAGENT_CHILD: "0", PI_SUBAGENTS_HERDR_BRIDGE: "0" };
  const verify = value => { writeFileSync(evidence, JSON.stringify(value)); return spawnSync(process.execPath, [harness.pathname, "verify-ledger", "--evidence", evidence], { env, encoding: "utf8" }); };
  assert.equal(verify(complete).status, 0);
  for (const after of [0, 1, 2]) { const value = structuredClone(complete); value.providerRequests.baseline.after = after; assert.equal(verify(value).status, 0); }
  const verifyAssistedAfter = after => { const value = structuredClone(complete), file = artifacts[4].terminal.path, original = readFileSync(file), record = JSON.parse(original); value.providerRequests.assisted.after = after; value.noWake.providerRequests.before.after = after; value.noWake.providerRequests.after.after = after; record.providerBefore.after = after; record.providerAfter.after = after; const bytes = `${JSON.stringify(record, null, 2)}\n`; writeFileSync(file, bytes); value.attemptArtifacts[4].terminal.sha256 = sha256(bytes); const result = verify(value); writeFileSync(file, original); return result; };
  for (const after of [0, 1]) assert.equal(verifyAssistedAfter(after).status, 0);
  const rejects = mutate => { const value = structuredClone(complete); mutate(value); assert.notEqual(verify(value).status, 0); };
  const artifactReject = (index, kind, mutate) => { const file = artifacts[index][kind].path, original = readFileSync(file), record = JSON.parse(original); mutate(record); const bytes = `${JSON.stringify(record, null, 2)}\n`, value = structuredClone(complete); writeFileSync(file, bytes); value.attemptArtifacts[index][kind].sha256 = sha256(bytes); assert.notEqual(verify(value).status, 0); writeFileSync(file, original); };
  rejects(value => { value.evidenceReservation.path = "/definitely/missing/pilot.json.reservation.json"; });
  rejects(value => { value.attemptArtifacts[0].issued.path = "/definitely/missing/001-issued.json"; });
  rejects(value => { value.attemptArtifacts[0].sequence = 7; });
  rejects(value => { value.attemptArtifacts[0].issued = value.attemptArtifacts[1].issued; });
  rejects(value => { value.attemptArtifacts[5].terminal.path = path.join(dir, "../outside.json"); });
  rejects(value => { value.usage[4].requestId = value.usage[2].requestId; value.usage[4].ownerRunId = value.usage[2].ownerRunId; value.usage[4].nodeId = value.usage[2].nodeId; });
  rejects(value => { delete value.usage[4].ownerRunId; });
  const duplicate = structuredClone(complete), duplicateTerminal = artifacts[5].terminal.path, duplicateOutcome = artifacts[5].outcome.path, originalTerminal = readFileSync(duplicateTerminal), originalOutcome = readFileSync(duplicateOutcome);
  duplicate.usage[4].requestId = "r1"; duplicate.usage[4].ownerRunId = "o1"; duplicate.usage[4].nodeId = "n1";
  for (const [kind, file, original] of [["terminal", duplicateTerminal, originalTerminal], ["outcome", duplicateOutcome, originalOutcome]]) { const record = JSON.parse(original); record.requestId = "r1"; record.ownerRunId = "o1"; record.nodeId = "n1"; const bytes = `${JSON.stringify(record, null, 2)}\n`; writeFileSync(file, bytes); duplicate.attemptArtifacts[5][kind].sha256 = sha256(bytes); }
  assert.notEqual(verify(duplicate).status, 0); writeFileSync(duplicateTerminal, originalTerminal); writeFileSync(duplicateOutcome, originalOutcome);
  rejects(value => { value.providerRequests.assisted = { before: 99, after: 100 }; });
  rejects(value => { value.providerRequests.baseline.before = 1; });
  rejects(value => { delete value.providerRequests.baseline.after; });
  rejects(value => { value.providerRequests.baseline.after = -1; });
  rejects(value => { value.providerRequests.baseline.after = 0.5; });
  rejects(value => { value.providerRequests.baseline.after = 3; });
  rejects(value => { value.noWake.providerRequests.after.after = 2; });
  rejects(value => { value.noWake.graceMs = 4999; });
  artifactReject(5, "issued", record => { record.contractHash = "bogus-not-a-hash"; });
  artifactReject(2, "issued", record => { record.requestedModel = "openai-codex/gpt-5.6-sol:off"; });
  artifactReject(2, "issued", record => { record.requestedThinking = "high"; });
  rejects(value => { value.usage[2].model = "openai-codex/gpt-5.6-sol"; });
  rejects(value => { value.usage[2].preflight.resolvedModel = "openai-codex/gpt-5.6-sol:high"; });
  rejects(value => { value.usage[2].observer.startupEntrySummary.push({ type: "message", role: "user" }); });
  rejects(value => { delete value.usage[2].observer.postTurnEntrySummary; });
  rejects(value => { value.usage[2].observer.postTurnCaptureCount = 2; });
  rejects(value => { value.usage[2].observer.postTurnEntrySummary.push({ type: "message", role: "assistant" }); });
  const consistentChildIdentityReject = (model, thinking) => { const value = structuredClone(complete), file = artifacts[2].terminal.path, original = readFileSync(file), record = JSON.parse(original); for (const target of [value.usage[2], record]) { target.model = model; target.thinking = thinking; target.preflight.resolvedModel = model; target.preflight.thinking = thinking; } const bytes = `${JSON.stringify(record, null, 2)}\n`; writeFileSync(file, bytes); value.attemptArtifacts[2].terminal.sha256 = sha256(bytes); assert.notEqual(verify(value).status, 0); writeFileSync(file, original); };
  consistentChildIdentityReject("openai-codex/gpt-5.6-sol", "off");
  consistentChildIdentityReject("openai-codex/gpt-5.6-sol:high", "high");
  const parentIdentityReject = () => { const value = structuredClone(complete), file = artifacts[0].terminal.path, original = readFileSync(file), record = JSON.parse(original); for (const target of [value.usage[0], record]) { target.model = "gpt-5.6-not-sol"; target.responses[0].model = "gpt-5.6-not-sol"; } const bytes = `${JSON.stringify(record, null, 2)}\n`; writeFileSync(file, bytes); value.attemptArtifacts[0].terminal.sha256 = sha256(bytes); assert.notEqual(verify(value).status, 0); writeFileSync(file, original); };
  parentIdentityReject();
  artifactReject(2, "terminal", record => { delete record.observer; });
  artifactReject(2, "terminal", record => { record.launchContractDigest = "bogus"; });
  artifactReject(2, "terminal", record => { record.unresolved = true; });
  artifactReject(2, "outcome", record => { record.validation.ok = false; });
  artifactReject(4, "terminal", record => { record.rawMessageCount = 1; });
  artifactReject(4, "terminal", record => { record.providerAfter.after = 2; });
  rejects(value => { value.attemptArtifacts[0].issued.sha256 = sha256(JSON.stringify({ kind: "issued" })); });
  const reservationOriginal = readFileSync(reservationPath); writeFileSync(reservationPath, `${reservationOriginal} `); assert.notEqual(verify(complete).status, 0); writeFileSync(reservationPath, reservationOriginal);
  const tampered = artifacts[0].terminal.path, original = readFileSync(tampered); writeFileSync(tampered, `${original} `); assert.notEqual(verify(complete).status, 0); writeFileSync(tampered, original);
  const missing = artifacts[1].outcome.path, missingMoved = `${missing}.moved`; renameSync(missing, missingMoved); assert.notEqual(verify(complete).status, 0); renameSync(missingMoved, missing);
  const moved = `${tampered}.moved`; renameSync(tampered, moved); symlinkSync(moved, tampered); assert.notEqual(verify(complete).status, 0); unlinkSync(tampered); renameSync(moved, tampered);
  const runtimeMoved = `${runtimePath}.moved`; renameSync(runtimePath, runtimeMoved); symlinkSync(runtimeMoved, runtimePath); assert.notEqual(verify(complete).status, 0); unlinkSync(runtimePath); renameSync(runtimeMoved, runtimePath);
  assert.equal(verify(complete).status, 0);
});
test("AC6 rejects invalid UTF-8, task controls, and overlong authority leases", () => { const root = mkdtempSync(path.join(tmpdir(), "autonoxis-contract-")); const invalid = path.join(root, "invalid.json"); const bytes = Buffer.from(`{"version":1,"authorityId":"a1","expiresAt":"${new Date(Date.now() + 60_000).toISOString()}","cwd":"${root}","model":"openai-codex/gpt-5.6-sol","nodes":[{"id":"n1","actor":"sorter","task":"`); writeFileSync(invalid, Buffer.concat([bytes, Buffer.from([0xff]), Buffer.from(`","expectedJson":{},"timeoutMs":1}]}`)])); assert.throws(() => loadContract(invalid, sha256(readFileSync(invalid)), root), /contract_utf8_invalid/); assert.throws(() => validateContract({ ...fixture(root), nodes: [{ ...fixture(root).nodes[0], task: "bad\u001btask" }] }), /contract_schema_invalid/); assert.throws(() => validateContract({ ...fixture(root), expiresAt: "2035-01-01T00:00:00.000Z" }), /contract_cwd_or_expiry_invalid/); });
test("AC7 check refuses unless arbiter rescue is explicitly disabled", () => { const harness = new URL("./native-harness.mjs", import.meta.url); const env = { ...process.env, PI_SUBAGENT_CHILD: "0", PI_SUBAGENTS_HERDR_BRIDGE: "0" }; delete env.PI_SUBAGENTS_LLM_INTENT_ARBITER; const result = spawnSync(process.execPath, [harness.pathname, "check"], { env, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /llm_intent_arbiter_not_disabled/); });
test("AC2 configured contract rejects legacy actor and digest fields", () => { const value = fixture(mkdtempSync(path.join(tmpdir(), "autonoxis-schema-"))); assert.throws(() => validateContract({ ...value, version: 1 }), /contract_schema_invalid/); assert.throws(() => validateContract({ ...value, agentDefinitionDigest: "bad" }), /contract_schema_invalid/); assert.throws(() => validateContract({ ...value, nodes: [{ ...value.nodes[0], actor: "sorter" }] }), /contract_schema_invalid/); });
test("AC2 shipped agent bytes are frozen", () => { assert.equal(sha256(readFileSync(new URL("../agents/sol-leaf.md", import.meta.url))), SHIPPED_AGENT_FILE_SHA256); });
test("AC2 public preflight detects an extensions-frontmatter omission", () => { const harness = new URL("./native-harness.mjs", import.meta.url); const env = { ...process.env, PI_SUBAGENT_CHILD: "1", PI_SUBAGENTS_HERDR_BRIDGE: "0" }; const run = (agentDir) => { const runRoot = mkdtempSync(path.join(tmpdir(), "autonoxis-frontmatter-")); const result = spawnSync(process.execPath, [harness.pathname, "print-agent-identity", "--run-root", runRoot, "--agent-dir", agentDir], { env, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); return JSON.parse(result.stdout).tools; }; const shipped = run(path.resolve(".")); const copied = mkdtempSync(path.join(tmpdir(), "autonoxis-agent-copy-")); cpSync(path.resolve("."), copied, { recursive: true }); const file = path.join(copied, "agents", "sol-leaf.md"); writeFileSync(file, readFileSync(file, "utf8").replace("extensions:\n", "")); const altered = run(copied); for (const key of ["explicitAllowlist", "effectiveAllowlist", "declaredBuiltin", "configuredExtensions", "excludeTools"]) assert.deepEqual(altered[key], shipped[key]); assert.equal(shipped.disableAmbientExtensions, true); assert.equal(altered.disableAmbientExtensions, false); });
test("AC5 stop revokes an asynchronously starting run before public imports settle", async () => { const root = mkdtempSync(path.join(tmpdir(), "autonoxis-start-")); const text = JSON.stringify(fixture(root)); const contract = path.join(root, "contract.json"); writeFileSync(contract, text); const agentDir = process.env.PI_CODING_AGENT_DIR || path.join(os.homedir(), ".pi", "agent"); const anchor = path.join(agentDir, "npm", "package.json"), { entry: piEntry } = resolvePinnedPiEntry(); const jiti = createRequire(anchor)("jiti")(anchor, { interopDefault: true, alias: { "@earendil-works/pi-coding-agent": piEntry } }); const plugin = (await jiti.import(path.resolve("./index.ts"))).default; const commands = {}; const notes = [], emits = []; plugin({ registerCommand: (name, command) => { commands[name] = command; }, on: () => {}, events: { on: () => () => {}, emit: (...args) => emits.push(args) }, appendEntry: () => {} }); const ctx = { cwd: root, sessionManager: { getSessionId: () => "parent", getEntries: () => [] }, ui: { notify: message => notes.push(message) } }; const running = commands.autonoxis.handler(`run ${contract} ${sha256(text)}`, ctx); await commands.autonoxis.handler("stop", ctx); await running; await commands.autonoxis.handler(`run ${contract} ${sha256(text)}`, ctx); assert.ok(notes.includes("Autonoxis authority revoked; run starting.")); assert.ok(notes.includes("run_busy")); assert.equal(emits.length, 0); });
test("AC5 reload treats terminal-only evidence as a consumed session run", async () => { const root = mkdtempSync(path.join(tmpdir(), "autonoxis-reload-")); const text = JSON.stringify(fixture(root)); const contract = path.join(root, "contract.json"); writeFileSync(contract, text); const agentDir = process.env.PI_CODING_AGENT_DIR || path.join(os.homedir(), ".pi", "agent"), anchor = path.join(agentDir, "npm", "package.json"), { entry: piEntry } = resolvePinnedPiEntry(); const jiti = createRequire(anchor)("jiti")(anchor, { interopDefault: true, alias: { "@earendil-works/pi-coding-agent": piEntry } }), plugin = (await jiti.import(path.resolve("./index.ts"))).default; const commands = {}, hooks = {}, notes = [], entries = [{ type: "custom", customType: "autonoxis-terminal", data: { status: "failed" } }]; plugin({ registerCommand: (name, command) => { commands[name] = command; }, on: (name, handler) => { hooks[name] = handler; }, events: { on: () => () => {}, emit: () => {} }, appendEntry: () => {} }); const ctx = { cwd: root, sessionManager: { getSessionId: () => "parent", getEntries: () => entries }, ui: { notify: message => notes.push(message) } }; hooks.session_start({}, ctx); await commands.autonoxis.handler(`run ${contract} ${sha256(text)}`, ctx); assert.ok(notes.includes("run_busy")); });
