import assert from "node:assert/strict";
import test from "node:test";
import { buildPolicyPacket, parseDecision, policyConfig, requestPolicy } from "../policy.mjs";

const promptPath = new URL("../prompts/conductor-system-v4.txt", import.meta.url);
const decisionResponse = () => new Response(JSON.stringify({ message: { content: "DECISION: DISPATCH" } }));

test("AC4 parses only exact, unambiguous decisions", () => { assert.equal(parseDecision("DECISION: DISPATCH\nignored", "DECISION", ["STOP", "ASK", "DISPATCH"]), "DISPATCH"); assert.throws(() => parseDecision("DECISION: dispatch", "DECISION", ["DISPATCH"]), /policy_response_invalid/); assert.throws(() => parseDecision("DECISION: DISPATCH\nDECISION: ASK", "DECISION", ["STOP", "ASK", "DISPATCH"]), /policy_response_invalid/); assert.throws(() => parseDecision("ACTION: ACCEPT\nACTION: REJECT", "ACTION", ["ACCEPT", "REJECT"]), /policy_response_invalid/); assert.throws(() => parseDecision(undefined, "DECISION", ["DISPATCH"]), /policy_response_invalid/); });
test("AC4 freezes loopback policy configuration", () => { assert.equal(policyConfig.endpoint, "http://127.0.0.1:11434/api/chat"); });
test("AC4 rejects malformed and oversized policy data", async () => { await assert.rejects(requestPolicy({ promptPath, packet: {}, fetchImpl: async () => new Response(JSON.stringify({ message: { content: "no" } })) }), /policy_response_invalid/); assert.throws(() => buildPolicyPacket("x".repeat(policyConfig.maxPacketBytes + 1)), /policy_packet_too_large/); await assert.rejects(requestPolicy({ promptPath, packet: "x", fetchImpl: async () => new Response("x".repeat(policyConfig.maxResponseBytes + 1)) }), /policy_response_too_large/); });
test("AC4 sends prose packets and requests redirect failure", async () => { let content, redirect; await requestPolicy({ promptPath, packet: "Human authority is current.", fetchImpl: async (_url, init) => { content = JSON.parse(init.body).messages[1].content; redirect = init.redirect; return decisionResponse(); } }); assert.equal(content, "Human authority is current."); assert.equal(redirect, "error"); assert.equal(buildPolicyPacket({ node: "n" }), '{"node":"n"}'); });
test("AC4 fails closed on outage and non-2xx responses", async () => { await assert.rejects(requestPolicy({ promptPath, packet: "x", fetchImpl: async () => { throw new Error("ollama_down"); } }), /ollama_down/); await assert.rejects(requestPolicy({ promptPath, packet: "x", fetchImpl: async () => new Response("down", { status: 503 }) }), /ollama_http_503/); });
test("AC4 aborts on external cancellation and timeout", async () => { const waitingFetch = async (_url, init) => await new Promise((_resolve, reject) => { if (init.signal.aborted) return reject(new DOMException("Aborted", "AbortError")); init.signal.addEventListener("abort", () => reject(new DOMException("Aborted", "AbortError")), { once: true }); }); const external = new AbortController(); const cancelled = requestPolicy({ promptPath, packet: "x", fetchImpl: waitingFetch, signal: external.signal }); external.abort(); await assert.rejects(cancelled, /AbortError/); await assert.rejects(requestPolicy({ promptPath, packet: "x", fetchImpl: waitingFetch, timeoutMs: 1 }), /AbortError/); });
